./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=1" -Output=1    -API=15  -Size="4.3" -Den=xhdpi   -ID=001
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=2" -Output=2    -API=18  -Size="7" -Den=xxhdpi  -ID=002
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=3" -Output=3    -API=18  -Size="4" -Den=hdpi    -ID=003
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=4" -Output=4    -API=15  -Size="4.3" -Den=xhdpi   -ID=004
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=5" -Output=5    -API=19  -Size="4.7" -Den=xxhdpi  -ID=005
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=6" -Output=6    -API=17  -Size="4.3" -Den=xxhdpi  -ID=006
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=8" -Output=8    -API=15  -Size="4.7" -Den=tvdpi   -ID=008
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=9" -Output=9    -API=19  -Size="5" -Den=xxhdpi  -ID=009
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=10" -Output=10   -API=15  -Size="4.3" -Den=xhdpi   -ID=010
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=11" -Output=11   -API=15  -Size="4.3" -Den=xhdpi   -ID=011
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=12" -Output=12   -API=18  -Size="4.5" -Den=xhdpi   -ID=012
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=13" -Output=13   -API=17  -Size="6" -Den=tvdpi   -ID=013
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=14" -Output=14   -API=15  -Size="4.7" -Den=xhdpi   -ID=014
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=15" -Output=15   -API=17  -Size="6" -Den=xhdpi   -ID=015
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=16" -Output=16   -API=19  -Size="5" -Den=xxhdpi  -ID=016
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=17" -Output=17   -API=19  -Size="5.5" -Den=xxxhdpi -ID=017
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=18" -Output=18   -API=15  -Size="4.3" -Den=xhdpi   -ID=018
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=19" -Output=19   -API=19  -Size="4.7" -Den=xhdpi   -ID=019
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=20" -Output=20   -API=16  -Size="10.1" -Den=mdpi    -ID=020
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=21" -Output=21   -API=18  -Size="5.7" -Den=xxhdpi  -ID=021
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=22" -Output=22   -API=17  -Size="4.99" -Den=xxhdpi  -ID=022
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=23" -Output=23   -API=19  -Size="5.1" -Den=xxhdpi  -ID=023
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=24" -Output=24   -API=16  -Size="5.5" -Den=xhdpi   -ID=024
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=25" -Output=25   -API=16  -Size="4.8" -Den=xhdpi   -ID=025
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=26" -Output=26   -API=16  -Size="10.1" -Den=hdpi    -ID=026
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=27" -Output=27   -API=15  -Size="4" -Den=hdpi    -ID=027 
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=28" -Output=28   -API=15  -Size="4.3" -Den=hdpi    -ID=028
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=96" -Output=96   -API=18  -Size="5" -Den=xhdpi   -ID=096
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=97" -Output=97   -API=18  -Size="5" -Den=xxhdpi  -ID=097
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=98" -Output=98   -API=18  -Size="4.8" -Den=hdpi    -ID=098
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=99" -Output=99   -API=19  -Size="5" -Den=xxhdpi  -ID=099
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=100" -Output=100   -API=17  -Size="6" -Den=xhdpi   -ID=100
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=101" -Output=101   -API=17  -Size="5.1" -Den=xxhdpi  -ID=101
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=102" -Output=102   -API=18  -Size="5.5" -Den=xxxhdpi -ID=102
./qrcode_gen_1  -Url="/DeviceManagerment/Edit?Status=Update&ID=103" -Output=103   -API=19  -Size="5" -Den=xxhdpi -ID=103
